name: vendor_catalogue_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.2
  encrypt: ^5.0.3
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  equatable: ^2.0.7
  http: ^1.3.0
  get_it: ^8.0.3
  intl: ^0.19.0
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.5
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  marquee: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: null
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/app_logo/app_logo.png"

flutter_gen:
  output: lib/config/assets/
  line_length: 80

  assets:
    enabled: true

    outputs:
      class_name: AppAssets
      package_parameter_enabled: false
      style: dot-delimiter

  fonts:
    enabled: true
    outputs:
      class_name: AppFonts

flutter:
  uses-material-design: true
  generate: true


  fonts:
    - family: worksans
      fonts:
        - asset: assets/font/WorkSans-ExtraLight.ttf
          weight: 100
        - asset: assets/font/WorkSans-Light.ttf
          weight: 200
        - asset: assets/font/WorkSans-Regular.ttf
          weight: 300
        - asset: assets/font/WorkSans-Medium.ttf
          weight: 400
        - asset: assets/font/WorkSans-SemiBold.ttf
          weight: 500
        - asset: assets/font/WorkSans-Bold.ttf
          weight: 600
        - asset: assets/font/WorkSans-ExtraBold.ttf
          weight: 700
        - asset: assets/font/WorkSans-Black.ttf
          weight: 800

  assets:
    - assets/app_logo/
    - assets/font/